name: tonometr
description: "Note your blood pressure"
publish_to: "none"
version: 0.1.0+4

environment:
  sdk: ^3.7.2

workspace:
  - packages/storage/storage
  - packages/storage/persistent_storage

dependencies:
  auto_route: ^10.1.0+1
  device_info_plus: ^11.5.0
  drift: ^2.16.0
  equatable: ^2.0.7
  file_picker: ^8.0.0+1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  package_info_plus: ^8.1.4
  path: ^1.8.3
  path_provider: ^2.1.2
  persistent_storage:
    path: packages/storage/persistent_storage
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.15
  storage:
    path: packages/storage/storage
  table_calendar: ^3.0.9
  talker: ^4.9.1
  talker_bloc_logger: ^4.9.1
  talker_flutter: ^4.9.1
  xml: ^6.5.0

dev_dependencies:
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  drift_dev: ^2.16.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
