name: tonometr
description: "Note your blood pressure"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

workspace:
  - packages/storage/storage
  - packages/storage/persistent_storage

dependencies:
  auto_route: ^9.2.2
  device_info_plus: ^11.5.0
  drift: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  package_info_plus: ^8.1.4
  path: ^1.8.3
  path_provider: ^2.1.2
  persistent_storage:
    path: packages/storage/persistent_storage
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  storage:
    path: packages/storage/storage
  talker: ^4.9.1
  talker_bloc_logger: ^4.9.1
  talker_flutter: ^4.9.1

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
