name: storage
description: A Key/Value Storage Client for Dart.
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
